name: Hprofile Actions
#on: workflow_dispatch   # [push, workflow_dispatch]
on:
  pull_request:
    types:
      - closed # Trigger the workflow when a pull request is closed
env:
  AWS_REGION: us-east-1
jobs: 

  If_merged:
    if: github.event.pull_request.merged == true # Check if the pull request was merged
    runs-on: ubuntu-latest # Specify the runner
    steps:
    - run: |
        echo The PR was merged # Print a message if the pull request was merged

  Testing:
    if: false # This condition effectively skips the job
    needs: If_merged
    runs-on: ubuntu-latest
    steps:
    
      - name: code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test
        
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

  Sonar:
    if: false # This condition effectively skips the job
    needs: Testing
    runs-on: ubuntu-latest
    steps:    
      # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner 
           -Dsonar.host.url=${{ secrets.SONAR_URL }} 
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}   
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} 
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}  
           -Dsonar.sources=src/  
           -Dsonar.junit.reportsPath=target/surefire-report/ 
           -Dsonar.jacoco.reportsPath=target/jacoco.exec   
           -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml  
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }} #OPTIONAL

  BUILD_AND_PUBLISH:
#    if: false # This condition effectively skips the job
#    needs: Testing
    needs: If_merged
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4  
    
#      - name: Update application.properties file
#        run: |
#          sed -i "s/^jdbc.username.*$/jdbc.username\=${{ secrets.RDS_USER }}/" src/main/resources/application.properties
#          sed -i "s/^jdbc.password.*$/jdbc.password\=${{ secrets.RDS_PASS }}/" src/main/resources/application.properties
#          sed -i "s/db01/${{ secrets.RDS_ENDPOINT }}/" src/main/resources/application.properties

      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          registry: ${{ secrets.REGISTRY }}
#          repo: docker
#          region: ${{ env.AWS_REGION }}
#          tags: ${{ github.run_number }}                #latest,${{ github.run_number }}
          daemon_off: false
#          dockerfile: ./Dockerfile
#          context: ./
#        run: |
#          docker build -t $registry:$repo:$tags .
#          docker push $registry:$repo:$tags

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 637423293208.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }} .
      
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest 637423293208.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}
      
      - name: Push Docker image to ECR
        run: |
          docker push 637423293208.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}


      - name: Update Image tag
        run: |
          sed -i "s|image:.*|image: 637423293208.dkr.ecr.us-east-1.amazonaws.com/docker:${{ github.run_number }} |" ./java.yaml

      - name: Commit changes
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_MAIL }}
          git add java.yaml
          git commit -m "Update image to ${{ github.run_number }}"
          git push
